### ISSUE TITLE
Remove the notion of attributes

### ISSUE THREAD

**Issue by vlad-lubenskyi** [SpineEventEngine/users#17]
The idea of attributes (in `User`, `Group`, `Organization`, and `OrgUnit` aggregates) was to store
custom information provided by the upstream users system.

For example, if `Company A` supplies all of its Exchange users with a custom property (let's say `alias`) this is a good candidate to be reflected as an attribute.

It was decided, however, not to use attributes for that. Rather, handle such domain-specific details in aggregate parts.

**Comment by alexander-yevsyukov** [comment]
Already addressed.
